[project]
name = "juckler-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "alembic",
    "psycopg2-binary",
    "pydantic-settings",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "ruff",
]